name: 'Better Code Owners'
description: 'Gerrit-style code owners for GitHub PRs'
author: 'Darryl Johnson'
inputs:
  github-token:
    description: 'GitHub Token (defaults to GITHUB_TOKEN env var)'
    required: false
  status-context:
    description: 'The name of the commit status to create'
    required: false
    default: 'Code Owner Approval'
runs:
  using: 'node20'
  main: 'dist/index.js'
branding:
  icon: 'shield'
  color: 'blue'
